### ISSUE TITLE
Joystick Control

### ISSUE THREAD

**Issue by chrisjedwards5** [NIURoverTeam/Electrical_Firmware#3]
Joystick control of some kind would be far superior than the current serial monitor control. 

Serial monitor control is very limited and slows operation.

**Comment by RyanTheRobothead** [comment]
Thinking about this, I think the best approach is to tackle #2 and then use ROS's Joystick package and a python node to blast over serial the same way I'm doing with the Rover5.

**Comment by chrisjedwards5** [comment]
Sounds good, if we can get that done we can remove the feather from the system which would be nice.

**Comment by RyanTheRobothead** [comment]
So, just to make sure I understand this correctly, is the plan that the PDCB will replace the feather?

**Comment by chrisjedwards5** [comment]
done :)
